version: '2'
services:
  jenkins:
    image: 'bitnami/jenkins:2'
    ports:
      - '8080:8080'
      - '50000:50000'
    restart: always
    volumes:
      - './jenkins_data:/bitnami'
      - '/root/projects:/projects'

volumes:
  jenkins_data:
    driver: local
